name: client
description: client
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.2.0
  collection: ^1.15.0
  server:
    path: ../server/

dev_dependencies:
  pedantic: ^1.10.0
