name: server
description: server
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.10.0
dependencies:
  async: ^2.8.1
  grpc: ^3.0.0
  vm_service: ^7.2.0
  watcher: ^1.0.0
